### ISSUE TITLE
Docker & GVM 22.4 on Ubuntu 22.4: Community install script is broken. (credential scanning now not working but last week it did))

### ISSUE THREAD

**Issue by itiligent** [greenbone/greenbone-container-images#2] opened 2022-09-01 13:36 UTC
Issue #1 appears to be quite prematurely closed and the response does not refelect the observations I'm trying to report.  

If you follow the script on the community page EXACTLY as docmenterd  (on Ubuntu 22.04) a missing docker compose dependency is still reported – EVEN THOUOUGH THE PIP version of docker compose IS installed. Thus the respose given around version requirements in issue #1 seems incorrect. Does this have any bearing on SMB credential scanning anyway? Everytghing else in scanning seems to work, just not credentials. In the rush to close things out I dont think both of these points havbe been teased out.  

Its easy to reproduce. The script will not allow the installation to progress without also adding apt install docker compose - so what to do?

**Comment by y0urself** [comment] 2022-09-01 14:49
As mentioned in https://forum.greenbone.net/t/latest-docker-22-4-worked-great-last-week-now-is-suddenly-unstable-and-broken/12941 your issue doesn't seem to be related to the recent changes in the docker images.


Also I do not get the relation between a possible missing docker-compose installation and the SMB credential scanning.

**Comment by bjoernricks** [comment] 2022-09-01 14:55
Also I didn't close your issue because it is invalid. I wanted to get to discussion to https://forum.greenbone.net/t/latest-docker-22-4-worked-great-last-week-now-is-suddenly-unstable-and-broken/12941 as this is not the correct place to discuss the issue.

**Comment by itiligent** [comment] 2022-09-01 15:10
There is great deal of miscommunication here I think.

There is definitely an issue with the credentials scanning which I’m trying to highlight. Version 22.04 on docker has recently become broken, this is a fact that I can replicate over and over. I am trying to report this and seek help.

The other matter of the docker compose dependency is a separate issue that I raised, that I suggested is unrelated. I’m also trying to raise that as a second issue with you. – again, it’s a fact and easily replicated.

Somehow these to items have become conflated.

My main concern right now is that credentials scanning become broken some time this week. What do and where to get help?   Are you interesting in knowing more about my testing?

**Comment by y0urself** [comment] 2022-09-01 15:30
1. If you have two unrelated issues: Create two issues/posts in the forum to avoid miscommunication on your side.
2. for the docker issue: Please show us some terminal output, so we can help. Currently we can not reproduce your "easy to reproduce" issues, because you are not sharing the information
3. for the openvas SMB issue: We have communicated with the responsible persons and there have not been any changes on the code recently, please provide logs, that. help us reproduce your issues. Btw. this issue should be discussed in the forum or in www.github.com/greenbone/openvas-smb

**Comment by itiligent** [comment] 2022-09-01 16:49
I meant what I said about easy to reproduce. All I am doing here is playing back to you what is on your website.

To reproduce Docker issue is as follows:

On fresh Ubuntu 22.04

# Enter following commands:
sudo apt-get update && sudo apt-get install curl docker.io python3 python3-pip -y
python3 -m pip install --user docker-compose

curl -f -O https://greenbone.github.io/docs/latest/_static/setup-and-start-greenbone-community-edition.sh \
&& chmod u+x setup-and-start-greenbone-community-edition.sh \
&& ./setup-and-start-greenbone-community-edition.sh 22.4

# Output below shows the script error immediately when it is started:

***@***.***:~$ curl -f -O https://greenbone.github.io/docs/latest/_static/setup-and-start-greenbone-community-edition.sh \
> && chmod u+x setup-and-start-greenbone-community-edition.sh \
> && ./setup-and-start-greenbone-community-edition.sh 22.4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2391  100  2391    0     0   6993      0 --:--:-- --:--:-- --:--:--  7011
docker-compose is not available. See https://greenbone.github.io/docs/latest/22.4/container/#prerequisites.
***@***.***:~$

If I install  docker compose from apt – i.e.  sudo apt install docker-compose then the script completes and it installs even the Debian version is is incorrect.

**Comment by bjoernricks** [comment] 2022-09-02 07:09
I am closing this issue here. This is not the right place for discussion these issues. This repo is only about the additional container images not the Greenbone Community Containers as a whole. Please let us use https://forum.greenbone.net/t/latest-docker-22-4-worked-great-last-week-now-is-suddenly-unstable-and-broken/12941 now.

**Closed by bjoernricks** 2022-09-02 07:09 UTC
